name: CICD pipeline
on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]
jobs:
    tests:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:8.0
                ports:
                    - 3306:3306
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: test_db
                options: --health-cmd="mysqladmin ping"
        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP with PECL extension
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.4'
                extensions: mbstring, bcmath, ctype, fileinfo, json, tokenizer, xml, pdo, pdo_mysql, openssl, curl, zip, imagick, swoole

            - name: Cache Composer dependencies
              uses: actions/cache@v4
              with:
                path: vendor
                key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                restore-keys: |
                  ${{ runner.os }}-composer-

            - name: Copy .env file
              run: |
                cp .env.ci .env

            - name: Install dependencies
              run: |
                composer install -q --no-ansi \
                --no-interaction --no-scripts --no-progress

            - name: Generate application key
              run: |
                php artisan key:generate

            - name: Directory permissions
              run: |
                sudo chown -R $USER:$USER storage bootstrap/cache
                chmod -R 775 storage bootstrap/cache

            - name: phpstan
              run: |
                ./vendor/bin/phpstan analyse --level=5 --memory-limit=1G

            - name: phpinsights
              run: |
                php artisan insights --no-interaction \
                --min-quality=90 --min-complexity=90 \
                --min-architecture=90 --min-style=90 \
                --ansi --format=github-action

            - name: Show DB config
              run: |
                grep DB_ .env

            - name: Run tests
              run: |
                php artisan test

            - name: Deployment to Main Server
              if: github.ref == 'refs/heads/main'
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.MAIN_SSH_HOT }}
                username:  ${{ secrets.SSH_USER }}
                password:  ${{ secrets.SSH_PASS }}
                script: |
                  cd /var/www/htm/laravel-cicd && ./main_deploy.sh main
            - name: Deployment to Dev Server
              if: github.ref == 'refs/heads/dev'
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username:  ${{ secrets.SSH_USER }}
                password:  ${{ secrets.SSH_PASS }}
                script: |
                  cd /var/www/htm/laravel-cicd && ./main_deploy.sh main

